server:
  port: 8888
spring:
  application:
    name: config-server-atendeia
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pabllo007/config-repo-atendeia
          default-label: master
          clone-on-start: true
