server:
  port: 8888
spring:
  application:
    name: atendeia-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pabllo007/atendeia-config-repo
          default-label: master
          clone-on-start: true
          search-paths: .

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
