spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: jdbc:postgresql://host-do-banco-prd:5432/atendeia_user
    username: user_prd
    password: senha_prd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
